/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bookstore_service_BookStoreIntegration */

#ifndef _Included_com_bookstore_service_BookStoreIntegration
#define _Included_com_bookstore_service_BookStoreIntegration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bookstore_service_BookStoreIntegration
 * Method:    search
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bookstore_service_BookStoreIntegration_search
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
